### ISSUE TITLE
Quoted Object Keys

### ISSUE THREAD

**Issue by LeonardoGentile** [Benvie/JavaScriptNext.tmLanguage#128]
Given a literal
```
{
  unquotedKey : "hello",
  "quotedKey" : "hi"
}
```
The `unquotedKey` will be scoped as 
```
source.js 
meta.group.braces.curly 
constant.other.object.key.js 
string.unquoted.label.js
``` 
while the `"quotedKey"` will be scoped as 
```
source.js 
meta.group.braces.curly 
string.quoted.double.js
```
Now, I'd like to match both quoted and unquoted keys for give them a specific color. The problem is that the unquoted one is matched as simple `string.quoted.double.js` so if I change its color it will change in any part of the script (not what I want).

So I've tried to modify the language definition, in order to match quoted and unquote literal keys (in YAML).  

```yaml
literal-labels:
    patterns:
    - begin: |-
        (?x)
          (?<!\?)(?<!\?\s)(?=(
            ((')((?:[^']|\\')*)('))|
            ((")((?:[^"]|\\")*)("))
          )\s*:)
      end: ':'
      endCaptures:
        '0': {name: punctuation.separator.key-value.js}
      patterns:
      - include: '#literal-string'
    - name: constant.other.object.key.js
      # ORIGINAL
      # match: (?<!\.|\?|\?\s)\"([_$a-zA-Z][$\w]*)\s*\"(:)
      match: (?<!\.|\?|\?\s)(["']?[_$a-zA-Z][$\w]*["']?)\s*(:) # MY VERSION
      captures:
        # ORIGINAL
        # '1': {name: string.unquoted.label.js}
        '1': {name: string.label.js} # MY VERSION
        '2': {name: punctuation.separator.key-value.js}
```
I convert the YAML to PLIST with AAAPackageDev plugin but I have no luck in making this work. I always have match for the `unquotedKey`, the `"quotedKey"` will always be matched by `string.quoted.double.js`.

Most probably it is a problem of specificity..I guess. Any toughs?

Thanks
